### ISSUE TITLE
Something wrong with the Display

### ISSUE THREAD

**Issue by xXBlckHeartXx** [xoxfaby/BetterUI#155] opened 2022-12-17 11:10 UTC
*If you submit an incomplete bug report that doesn't follow this template completely, it will be closed without reading until you update the bug report with the missing info*

**Describe the bug**  
A clear description of what the bug is.

like 2 days ago it worked perfektly it showed me the whole and combined stats from the item stacks today it shows me the single stats and the stack "upgrade" frome the item but not the combined stats in total it just says as example for the gas tank:

BETTERUI_RADIUS: 16BETTERUI_RANGE_SUFFIX
BETTERUI_DAMAGE: 225BETTERUI_CHANCE_SUFFIX

i mean yes its the combined dmg and range of 2 gas tanks (16 range and 225 dmg) but it dosent look good

**Link your log file**  
You can find your log file under `Risk of Rain 2/BepInEx/LogOutput.log`

https://docs.google.com/document/d/1Nr0Wfu43eUOuxkpky92gKiU7yQJvD4zCs5NPHCqagSc/edit

**Does the error occur when only using BetterUI and no other mods?**  
Please test this before submitting a bug report. 
If the bug is related to another mod, please confirm if this bug happens with only BetterUI, the mod and any dependencies installed. 

its still there

**BetterUI Version**  
Which version of BetterUI you're using e.g.: v1.2.1

2.7.2

**Additional information**  

its not that bad (this issue i love the mod) but it looks kinda ugly tbh

picture is in the google doc data

**Comment by xoxfaby** [comment] 2022-12-21 06:33
Duplicate of #150

**Closed by xoxfaby** 2022-12-21 06:33 UTC
Labels: bug
