### ISSUE TITLE
Attempting to pick up an item does not remove it from the world.

### ISSUE THREAD

**Issue by Xyvyrianeth** [xoxfaby/BetterUI#7] opened 2020-09-12 17:06 UTC
It still gets put in your inventory, but it won't disappear from the ground. Fortunately, it doesn't allow for duplication, it's just annoying seeing things that aren't really there.
[onPickup.txt](https://github.com/xoxfaby/BetterUI/files/5212987/onPickup.txt)
[In action](https://im.ezgif.com/tmp/ezgif-1-97c2cbf4e223.gif)

**Comment by xoxfaby** [comment] 2020-09-12 17:13
Are you using any other mods?

**Comment by xoxfaby** [comment] 2020-09-12 20:03
I'm going to close this, feel free to open it and comment again if you are still experiencing this but I'm guessing this was caused by some other mod misbehaving. I also saw you have OrderedItems. If OrderedItems behaves correctly, it should work with my mod, but I'm assuming that it doesn't and that it's thereby causing issues. But my mod does everything OrderedItem does so I suggest removing it to solve this problem.

**Closed by xoxfaby** 2020-09-12 20:03 UTC
